/**********************************************************************
 *
 * Copyright (C) 2023 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED */ 


#ifndef _AW_NEXA_FACE_ERRORS_H_
#define _AW_NEXA_FACE_ERRORS_H_

/* Error Codes */

/* No errors or warnings. */
#define AW_NEXA_FACE_E_NO_ERRORS                            0

/* An internal error occurred. */
#define AW_NEXA_FACE_E_INTERNAL_ERROR                       1

/* The nexa_face object was NULL. */
#define AW_NEXA_FACE_E_NULL_NEXA_FACE_OBJ                   2

/* The trial expiration has passed. */
#define AW_NEXA_FACE_E_TRIAL_EXPIRATION_PASSED              3

/* The library failed to allocate memory. */
#define AW_NEXA_FACE_E_OUT_OF_MEMORY                        100

/* The nexa_face object was not initialized. */
#define AW_NEXA_FACE_E_NOT_INITIALIZED                      101

/* The nexa_face object was already initialized. */
#define AW_NEXA_FACE_E_ALREADY_INITIALIZED                  102

/* Worker count must be greater than or equal to 0. */
#define AW_NEXA_FACE_E_INVALID_WORKER_COUNT                 103

/* 32 bit and mobile systems only have enough memory for one worker. */
#define AW_NEXA_FACE_E_TOO_MANY_WORKERS                     104

/* Maximum encounters must be greater than 0 and less than 10000000. */
#define AW_NEXA_FACE_E_INVALID_MAXIMUM_ENCOUNTERS           105

/* This operation requires that an export callback is registered. */
#define AW_NEXA_FACE_E_NO_EXPORT_CALLBACK_REGISTERED        107

/* This operation requires that a compare result callback is registered. */
#define AW_NEXA_FACE_E_NO_COMPARE_RESULT_CALLBACK_REGISTERED 108

/* This operation requires that a verify result callback is registered. */
#define AW_NEXA_FACE_E_NO_VERIFY_RESULT_CALLBACK_REGISTERED 109

/* This operation requires that an identify result callback is registered. */
#define AW_NEXA_FACE_E_NO_IDENTIFY_RESULT_CALLBACK_REGISTERED 110

/* The job name is already being used by an existing job. */
#define AW_NEXA_FACE_E_JOB_NAME_IN_USE                      111

/* The specified algorithm is not valid. */
#define AW_NEXA_FACE_E_INVALID_ALGORITHM                    112

/* The specified algorithm is not enabled. */
#define AW_NEXA_FACE_E_ALGORITHM_NOT_ENABLED                113

/* No algorithms were enabled. */
#define AW_NEXA_FACE_E_NO_ALGORITHMS_ENABLED                114

/* Destroy has been called on this Nexa|Face instance. No new tasks are
   accepted. */
#define AW_NEXA_FACE_E_SHUTDOWN_ACTIVE                      115

/* The specified face type is not valid. */
#define AW_NEXA_FACE_E_INVALID_FACE_TYPE                    116

/* The specified face type is not enabled. */
#define AW_NEXA_FACE_E_FACE_TYPE_NOT_ENABLED                117

/* No face types were enabled. */
#define AW_NEXA_FACE_E_NO_FACE_TYPES_ENABLED                118

/* The specified algorithm is already enabled. */
#define AW_NEXA_FACE_E_ALGORITHM_ALREADY_ENABLED            119

/* A face set must contain one or more faces. */
#define AW_NEXA_FACE_E_EMPTY_FACE_SET                       120

/* The RAM cache type is not available on this platform. */
#define AW_NEXA_FACE_E_CACHE_TYPE_RAM_NOT_AVAILABLE         121

/* This operation requires that a cache         result callback is
   registered. */
#define AW_NEXA_FACE_E_NO_CACHE_RESULT_CALLBACK_REGISTERED  122

/* This operation requires that a cache result callback is registered. */
#define AW_NEXA_FACE_E_NO_CACHE_BATCH_RESULT_CALLBACK_REGISTERED 123

/* The specified algorithm cannot be used in a partial identify. */
#define AW_NEXA_FACE_E_ALGORITHM_CANNOT_BE_USED_IN_PARTIAL_IDENTIFY 125

/* The specified algorithm is not supported on the platform. */
#define AW_NEXA_FACE_E_ALGORITHM_NOT_SUPPORTED_ON_PLATFORM  126

/* The model file provided is not valid for the algorithm specified. */
#define AW_NEXA_FACE_E_INVALID_MODEL_FOR_ALGORITHM          127

/* There were no scores provided for fusion. */
#define AW_NEXA_FACE_E_NO_SCORES_PROVIDED_FOR_FUSION        128

/* The score and encounter count lists must be the same size. */
#define AW_NEXA_FACE_E_SCORES_AND_ENCOUNTER_COUNTS_NOT_EQUAL_SIZE 129

/* Max Identify thread count must be greater than or equal to 0. */
#define AW_NEXA_FACE_E_INVALID_MAX_IDENTIFY_THREAD_COUNT    130

/* Invalid encounter object. */
#define AW_NEXA_FACE_E_INVALID_ENCOUNTER                    200

/* The encounter is busy and cannot be modified. */
#define AW_NEXA_FACE_E_ENCOUNTER_BUSY                       201

/* Encounter has no image or template data. */
#define AW_NEXA_FACE_E_ENCOUNTER_HAS_NO_DATA                202

/* Import encounter does not have all of the required data. */
#define AW_NEXA_FACE_E_IMPORTED_ENCOUNTER_MISSING_DATA      203

/* Encounter has no ID. */
#define AW_NEXA_FACE_E_ENCOUNTER_HAS_NO_ID                  204

/* The imported template was invalid. */
#define AW_NEXA_FACE_E_INVALID_IMPORT_TEMPLATE              205

/* Encounter has no image or template data that can be used for this
   operation. */
#define AW_NEXA_FACE_E_ENCOUNTER_HAS_NO_RELEVANT_DATA       206

/* Invalid encounter ID. */
#define AW_NEXA_FACE_E_INVALID_ENCOUNTER_ID                 207

/* Invalid candidate list object. */
#define AW_NEXA_FACE_E_INVALID_CANDIDATE_LIST               240

/* Candidate list size must be greater than 0. */
#define AW_NEXA_FACE_E_INVALID_CANDIDATE_LIST_SIZE          241

/* Invalid compare result object. */
#define AW_NEXA_FACE_E_INVALID_COMPARE_RESULT               260

/* Invalid identify result object. */
#define AW_NEXA_FACE_E_INVALID_IDENTIFY_RESULT              280

/* Invalid workflow object. */
#define AW_NEXA_FACE_E_INVALID_WORKFLOW                     300

/* This workflow has no comparator. */
#define AW_NEXA_FACE_E_WORKFLOW_NO_COMPARATOR               301

/* The algorithm is already present in the workflow. An algorithm can only
   be used once as either a filter or a comparator. */
#define AW_NEXA_FACE_E_WORKFLOW_ALGORITHM_ALREADY_PRESENT   302

/* The fixed number used for a filter must be greater than 0. */
#define AW_NEXA_FACE_E_WORKFLOW_INVALID_FILTER_FIXED        303

/* The percentage used for a filter must be greater than 0 and less than or
   equal to 1.0. */
#define AW_NEXA_FACE_E_WORKFLOW_INVALID_FILTER_PERCENTAGE   304

/* This comparator cannot be used in this workflow. */
#define AW_NEXA_FACE_E_WORKFLOW_INVALID_COMPARATOR          305

/* Filters are not allowed for this operation. */
#define AW_NEXA_FACE_E_WORKFLOW_FILTERS_NOT_ALLOWED         306

/* The workflow has no faces set to be used. */
#define AW_NEXA_FACE_E_WORKFLOW_NO_FACES                    307

/* Invalid cache add batch object. */
#define AW_NEXA_FACE_E_INVALID_CACHE_ADD_BATCH              400

/* The cache add batch object is empty. */
#define AW_NEXA_FACE_E_EMPTY_CACHE_ADD_BATCH                401

/* The input image is invalid. */
#define AW_NEXA_FACE_E_INPUT_IMAGE_INVALID                  500

/* Failed to parse the input image. */
#define AW_NEXA_FACE_E_IMAGE_PARSE_FAILED                   520

/* The input raw image did not have the correct number of bytes. */
#define AW_NEXA_FACE_E_INVALID_RAW_IMAGE                    521

/* The raw version of the image is not 8 bit greyscale or 24 bit RGB. */
#define AW_NEXA_FACE_E_INVALID_BIT_DEPTH                    522

/* The image dimensions are too small. */
#define AW_NEXA_FACE_E_IMAGE_TOO_SMALL                      523

/* The image dimensions are too big. */
#define AW_NEXA_FACE_E_IMAGE_TOO_BIG                        524

/* No faces found in the input image. */
#define AW_NEXA_FACE_E_NO_FACES_FOUND                       530

/* An error occurred during face finding. */
#define AW_NEXA_FACE_E_FACE_FINDING                         531

/* An error occurred during face recognition. */
#define AW_NEXA_FACE_E_FACE_RECOGNITION                     532

/* The optimization model could not be found at the given path. */
#define AW_NEXA_FACE_E_OPTIMIZATION_MODEL_NOT_FOUND         533

/* The optimization model at the given path was not a valid optimization
   model. */
#define AW_NEXA_FACE_E_OPTIMIZATION_MODEL_INVALID           534

/* The template was created from a optimization model different than the one
   currently in use. */
#define AW_NEXA_FACE_E_TEMPLATE_WRONG_MODEL                 535

/* The template was created from an different version of the optimization
   model. */
#define AW_NEXA_FACE_E_TEMPLATE_WRONG_MODEL_VERSION         536

/* The template was created from an incompatible version of Nexa|Face. */
#define AW_NEXA_FACE_E_TEMPLATE_WRONG_VERSION               537

/* Invalid cache config object. */
#define AW_NEXA_FACE_E_INVALID_CACHE_CONFIG                 700

/* A cache with the same name is         already in use. */
#define AW_NEXA_FACE_E_CACHE_NAME_IN_USE                    701

/* A cache with the given name could not be found. */
#define AW_NEXA_FACE_E_CACHE_NAME_NOT_FOUND                 702

/* The cache config has no algorithms enabled. */
#define AW_NEXA_FACE_E_CACHE_CONFIG_NO_ALGORITHMS_ENABLED   703

/* An internal cache error occurred. */
#define AW_NEXA_FACE_E_CACHE_INTERNAL_ERROR                 1001

/* The ID already exists in the cache. */
#define AW_NEXA_FACE_E_CACHE_ID_EXISTS                      1006

/* The ID was not found in the cache. */
#define AW_NEXA_FACE_E_CACHE_ID_NOT_FOUND                   1007

/* The cache is corrupted. */
#define AW_NEXA_FACE_E_CACHE_CORRUPTED                      1010

/* The cache failed to perform an IO operation. */
#define AW_NEXA_FACE_E_CACHE_IO_FAILURE                     1011

/* The cache version on disk does not match the software version. */
#define AW_NEXA_FACE_E_CACHE_VERSION_MISMATCH               1012

/* The cache found is not a valid cache. */
#define AW_NEXA_FACE_E_CACHE_INVALID                        1013

/* The cache is empty. */
#define AW_NEXA_FACE_E_CACHE_EMPTY                          1014

/* The cache is full. */
#define AW_NEXA_FACE_E_CACHE_FULL                           1015

/* The cache reached the maximum number of client connections. */
#define AW_NEXA_FACE_E_CACHE_MAX_CONNECTIONS_REACHED        1016

/* The attempted cache operation was too large. */
#define AW_NEXA_FACE_E_CACHE_OPERATION_TOO_LARGE            1017

/* The cache file was configured with flags incompatible with the current
   settings. */
#define AW_NEXA_FACE_E_CACHE_INCOMPATIBLE                   1018

/* The cache operation failed due to a permission error. */
#define AW_NEXA_FACE_E_CACHE_PERMISSION_ERROR               1019

/* Invalid cache path. */
#define AW_NEXA_FACE_E_CACHE_INVALID_PATH                   1020

/* The cache has too many open files. */
#define AW_NEXA_FACE_E_CACHE_TOO_MANY_OPEN_FILES            1021

/* The cache file is too large. */
#define AW_NEXA_FACE_E_CACHE_FILE_TOO_LARGE                 1022

/* The disk has no free space remaining. */
#define AW_NEXA_FACE_E_CACHE_NO_FREE_SPACE                  1023

/* The cache path was too long. */
#define AW_NEXA_FACE_E_CACHE_PATH_TOO_LONG                  1024

/* A cache with algorithms stored in RAM cannot be on a remote drive. */
#define AW_NEXA_FACE_E_CACHE_RAM_CANNOT_BE_REMOTE           1025



#endif /* _AW_NEXA_FACE_ERRORS_H_ */
